# Default values for nexq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nexq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
args: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

configYaml: |
  initialUsers:
    - username: admin
      password: admin
      accessKeyId: key
      secretAccessKey: secret

  store:
    type: memory

  rest:
    http:
      bind: 0.0.0.0:7887

  prometheus:
    http:
      bind: 0.0.0.0:7889

  keda:
    bind: 0.0.0.0:7890

restService:
  enabled: true
  type: ClusterIP
  port: 7887

prometheusService:
  enabled: true
  type: ClusterIP
  port: 7889

kedaService:
  enabled: true
  type: ClusterIP
  port: 7890

ingress:
  enabled: false
  className: ""
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '7889'
  hosts:
    - host: nexq.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: nexq-tls
  #    hosts:
  #      - nexq.local

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /api/v1/info
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/info
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
