FROM mcr.microsoft.com/devcontainers/javascript-node:22

RUN apt-get update
RUN apt-get install -y awscli
RUN apt-get install -y python3-pip python3-venv
RUN apt-get install -y sqlite3
RUN apt-get install -y protobuf-compiler
