apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexq.fullname" . }}
  labels:
    {{- include "nexq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheusService.type }}
  ports:
    {{- if .Values.restService.enabled }}
    - port: {{ .Values.restService.port }}
      targetPort: {{ .Values.restService.port }}
      protocol: TCP
      name: rest
    {{- end }}
    {{- if .Values.prometheusService.enabled }}
    - port: {{ .Values.prometheusService.port }}
      targetPort: {{ .Values.prometheusService.port }}
      protocol: TCP
      name: prometheus
    {{- end }}
    {{- if .Values.kedaService.enabled }}
    - port: {{ .Values.kedaService.port }}
      targetPort: {{ .Values.kedaService.port }}
      protocol: TCP
      name: keda
    {{- end }}
  selector:
    {{- include "nexq.selectorLabels" . | nindent 4 }}