apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaled-object
spec:
  scaleTargetRef:
    name: test-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
    - type: external
      metadata:
        scalerAddress: nexq.default:7890
        # Name of the queue to monitor
        queueName: queue1
        # Value to start scaling for
        threshold: "5"
        # Target value for activating the scaler (default: 0)
        activationThreshold: "0"
