# configuration file accepts environment variable substitution using: "${env:USER}"

# This user is created on a store that has not yet been initialized
initialUsers:
  - username: admin
    password: admin
    accessKeyId: key
    secretAccessKey: secret

store:
  type: memory

##
## SQLite configuration
##
# store:
#   type: sql
#   dialect: sqlite
#   pollInterval: 30s

## the database connection string.
##     :memory: 	       Open an in-memory database.
##     data.db	         Open the file data.db in the current directory.
#   connectionString: ":memory:"

#
# Postgres configuration
#
# store:
#   type: sql
#   dialect: postgres
#   pollInterval: 30s
#   connectionString: "postgres://nexq-postgres/nexq"
#   options:
#     user: nexq
#     password: password

#
# REST protocol configuration
#
rest:
  http:
    bind: 0.0.0.0:7887
  # https:
  #   bind: 0.0.0.0:7888
  #   ca: ./certs/nexq-rootca.crt
  #   cert: ./certs/nexq.local.crt
  #   key: ./certs/nexq.local.key
  # auth:
  #   - type: basic

#
# Prometheus metrics protocol configuration
#
prometheus:
  http:
    bind: 0.0.0.0:7889
  # https:
  #   bind: 0.0.0.0:7890
  #   ca: ./certs/nexq-rootca.crt
  #   cert: ./certs/nexq.local.crt
  #   key: ./certs/nexq.local.key

#
# Keda metrics protocol configuration
#
keda:
  bind: 0.0.0.0:7890
  # ca: ./certs/nexq-rootca.crt
  # cert: ./certs/nexq.local.crt
  # key: ./certs/nexq.local.key
